name: qbit_shared
description: QBit Shared - 공통 UI 및 라우팅
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # 로컬 패키지
  qbit_core:
    path: ../core
  qbit_services:
    path: ../services
  
  # 라우팅
  go_router: ^16.2.4
  
  # 저장소
  flutter_secure_storage: ^9.2.2
  
  # UI
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
